import { ArrowUpRight, FileText, Award, GraduationCap, Globe2, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
const services = [
 { slug: "business-docs", label: "Business Docs", title: "Ideas with a clear direction.", text: "Research, business plans, policy documents and professional writing shaped around your objectives.", icon: FileText },
 { slug: "eb1a", label: "EB1A", title: "Give your achievements a voice.", text: "CV review and evidence-led writing support for extraordinary ability petition materials.", icon: Award },
 { slug: "eb1b", label: "EB1B", title: "Bring your academic impact into focus.", text: "Document and writing support for outstanding professors and researchers working with a U.S. employer.", icon: GraduationCap },
 { slug: "eb2", label: "EB2", title: "Articulate the value of your endeavor.", text: "Research and writing support for National Interest Waiver materials, including proposed endeavor and business plans.", icon: Globe2 },
];
export default function Home() {return <main id="main">
 <section className="hero wrap residence-hero"><div><h1>Professional Support for Your Path to <em>U.S. Permanent Residence</em></h1><p className="service-specialties">Research • Petition Documentation • Professional Writing • Coaching</p><p className="lead">Are you lawfully present in the United States with BSc, MSc or PhD and exploring an employment-based pathway toward permanent residence, or are you a qualified professional, researcher, entrepreneur, or business owner outside the United States seeking an opportunity to live and work in America?</p><p className="lead">Obotan Consult provides non-attorney immigration petition and professional documentation support for individuals exploring EB-1 and EB-2 NIW pathways.</p><div className="hero-actions"><Button asChild className="cta"><a href="#services">Explore our services <ArrowUpRight/></a></Button><a className="text-link" href="#how-it-works">How it works</a></div><p className="micro">No client account needed · 40-minute consultations</p></div>
 <aside className="hero-note"><div className="note-top"><span>THE OBOTAN APPROACH</span><span>01—03</span></div><h2>Strong documents.<br/>Built on<br/><em>your evidence.</em></h2>{[["01","Understand your story","Review your CV, goals and existing documents."],["02","Bring structure to your work","Connect research, facts and supporting materials."],["03","Write with purpose","Develop clear, well-organized documents."]].map(([n,t,p])=><div className="note-row" key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}<div className="note-bottom"><Check size={16}/> Research and writing support</div></aside></section>
 <section className="professional-intro wrap" aria-labelledby="our-services-heading">
   <p className="team-introduction">Our multidisciplinary team brings expertise in research, academia, engineering, technology, cybersecurity, business, operations, policy research, and professional writing. We take time to understand your professional background, accomplishments, evidence, and future plans before helping you research, organize, document, and professionally present your work.</p>
   <h2 id="our-services-heading">Our Services</h2>
   <div className="service-detail-grid">
     <article><span className="eyebrow">01 / DOCUMENTATION</span><h3>Immigration Petition Support</h3><p>We provide non-attorney document-preparation support for EB-1A, EB-1B, and EB-2 NIW petitions. Our services include supporting potential employment-based applicants to prepare their petition documents, evidence organization, exhibit preparation, proposed-endeavor development, recommendation and expert-opinion letters, professional achievement narratives, supporting research, and RFE-response documentation.</p></article>
     <article><span className="eyebrow">02 / BUSINESS DEVELOPMENT</span><h3>Business Plans & U.S. Implementation Strategies</h3><p>We develop professional business plans and U.S. implementation strategies for entrepreneurs, business owners, consultants, and professionals whose proposed activities require a clear plan for implementation. Our work includes market opportunities, business operations, target industries, service models, financial projections, implementation milestones, workforce plans, growth strategies, and anticipated economic contributions.</p></article>
     <article><span className="eyebrow">03 / RESEARCH & WRITING</span><h3>Research & Professional Writing</h3><p>Our team provides industry research, business operations research, technical research, literature reviews, economic-impact analysis, professional reports, research summaries, and scholarly-documentation support. We also help professionals organize and explain their research, publications, technical projects, professional achievements, and practical contributions in a manner that can be understood beyond their immediate field.</p></article>
     <article><span className="eyebrow">04 / POLICY & INDUSTRY</span><h3>U.S. Policy & Industry Research</h3><p>We research authoritative materials that can help establish the broader importance and context of a client’s proposed work. This includes U.S. government policies, federal reports, government contracting and procurement materials, labor statistics, industry reports, economic data, national strategies, workforce needs, infrastructure challenges, and emerging industry opportunities.</p></article>
   </div>
 </section>
 <section className="services wrap" id="services"><div className="section-heading"><div><p className="eyebrow">HOW WE CAN HELP</p><h2>A clear path to your next step.</h2></div><p>Choose a service to learn more<br/>and start your consultation.</p></div><div className="service-grid">{services.map((s,i)=><a className="service-card" href={`/services/${s.slug}`} key={s.slug}><div className="card-top"><s.icon size={25} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{s.label}</h3><h4>{s.title}</h4><p>{s.text}</p><span className="card-link">Explore {s.label} <ArrowUpRight size={19}/></span></a>)}</div></section>
 <section className="process" id="how-it-works"><div className="wrap"><p className="eyebrow">FROM FIRST LOOK TO FIRST CONVERSATION</p><div className="section-heading"><h2>Start with what you have.</h2><p>Simple steps. A focused conversation.</p></div><div className="process-grid">{[["01","Tell us about your work","Choose a service and tick the evidence or document support relevant to you."],["02","Share your CV or brief","Attach your CV for immigration support, or describe your business document project."],["03","Make time for your next step","Choose an available 40-minute appointment to discuss your documents and writing needs."]].map(([n,t,d])=><div key={n}><span className="process-number">{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
 <section className="wrap closing obotan-message"><div><p className="eyebrow">A MESSAGE FROM OBOTAN CONSULT</p><h2>Your experience may be impressive, but the quality of its presentation matters.</h2><p>Our multidisciplinary approach brings together research, writing, coaching, and professional expertise to help you develop organized and evidence-based immigration documentation.</p><p>Whether you are preparing an EB-1A, EB-1B, or EB-2 NIW petition, developing a U.S. business, strengthening your professional profile, or require specialized research and supporting documentation, begin with a discussion with Obotan Consult.</p><p><em>At Obotan Consult, we provide non-attorney immigration consultancy, research, coaching, and document-preparation support services.</em></p><a className="text-link" href="#services">Begin a discussion <ArrowUpRight size={18}/></a></div></section>
 </main>}




