"use client";
import {useEffect,useState} from "react";
import {ArrowRight,ArrowLeft,CalendarDays,Clock3,FileText,CheckCircle2,Download,ShieldCheck,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Checkbox} from "@/components/ui/checkbox";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Service,evidenceOptions} from "@/lib/services";
import {Slot,calendarFile} from "@/lib/schedule";
type Result={reference:string;appointment:Slot};
export function Intake({service}:{service:Service}){
 const [step,setStep]=useState(1),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[field,setField]=useState(""),[notes,setNotes]=useState(""),[file,setFile]=useState<File|null>(null),[consent,setConsent]=useState(false),[website,setWebsite]=useState(""),[slots,setSlots]=useState<Slot[]>([]),[date,setDate]=useState(""),[chosen,setChosen]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[result,setResult]=useState<Result|null>(null),[id,setId]=useState("");
 const isBusiness=service.slug==="business-docs";
 useEffect(()=>{setId(crypto.randomUUID())},[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tool={name:"set_consultation_checklist",description:"Replace the self-reported checklist selections for this service. Does not submit information or book a meeting.",inputSchema:{type:"object",properties:{evidenceIds:{type:"array",items:{type:"string"}}},required:["evidenceIds"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const value=input as {evidenceIds?:unknown};const ids=value?.evidenceIds;if(!Array.isArray(ids)||ids.some(x=>typeof x!=="string"||!evidenceOptions(service).some(o=>o.id===x)))throw new Error("Use valid checklist IDs for this service.");setSelected([...new Set(ids)]);return {service:service.slug,selectedIds:[...new Set(ids)],submitted:false}}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[service]);
 async function loadSlots(){setLoading(true);setError("");try{const r=await fetch("/api/slots",{cache:"no-store"});const data=await r.json() as {slots:Slot[];error?:string};if(!r.ok)throw new Error(data.error);setSlots(data.slots);setDate(d=>data.slots.some((s:Slot)=>s.date===d)?d:data.slots[0]?.date||"");setChosen(c=>data.slots.some((s:Slot)=>String(s.start)===c)?c:"")}catch(e){setError(e instanceof Error?e.message:"Unable to load appointments.")}finally{setLoading(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");
  if(step===1){setStep(2);return}
  if(step===2){if(!isBusiness&&!file){setError("Attach your CV as a PDF to continue.");return}setStep(3);void loadSlots();return}
  if(!chosen){setError("Choose an appointment time.");return}if(!consent){setError("Please acknowledge the service scope and privacy information.");return}setSaving(true);
  const data=new FormData();for(const [k,v] of Object.entries({id,service:service.slug,name,email,phone,field,notes,evidence:JSON.stringify(selected),slot:chosen,consent:"yes",website}))data.set(k,v);if(file)data.set("cv",file);
  try{const r=await fetch("/api/submissions",{method:"POST",body:data});const body=await r.json() as Result & {error?:string};if(!r.ok){if(r.status===409){await loadSlots();setChosen("")}throw new Error(body.error||"Unable to save booking.")}setResult(body);setFile(null)}catch(e){setError(e instanceof Error?e.message:"Unable to save booking. Please try again.")}finally{setSaving(false)}
 }
 function chooseFile(f:File|undefined){if(!f)return;if(f.size>5*1024*1024||!f.name.toLowerCase().endsWith(".pdf")){setError("Choose a PDF no larger than 5 MB.");return}setFile(f);setError("")}
 function downloadCalendar(){if(!result)return;const url=URL.createObjectURL(new Blob([calendarFile(result.appointment.start,result.reference)],{type:"text/calendar;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="obotan-consultation.ics";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 if(result)return <div className="booking-success panel" role="status"><CheckCircle2 size={45}/><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Your consultation is booked.</h2><p className="lead">{result.appointment.fullLabel}</p><p>40 minutes · Research and writing support</p><div className="notice">Save this confirmation. Obotan will contact you at <strong>{email}</strong> with meeting details. An automated email has not been sent.</div><p className="tiny">Reference: {result.reference}</p><div className="hero-actions"><Button onClick={downloadCalendar} className="cta"><Download/> Add to calendar</Button><Button variant="outline" className="cta" asChild><a href="/">Return home</a></Button></div><p className="micro">For changes, email <a className="content-link" href="mailto:obotanconsult@gmail.com">obotanconsult@gmail.com</a> and include your reference.</p></div>;
 return <div className="intake-layout"><section><ol className="steps" aria-label="Consultation steps">{["Your checklist","Your documents","Your consultation"].map((s,i)=><li key={s} className={step===i+1?"active":step>i+1?"done":""} aria-current={step===i+1?"step":undefined}><span>{step>i+1?"✓":i+1}</span>{s}</li>)}</ol><form onSubmit={submit}>
 {step===1&&<div className="panel"><p className="eyebrow">STEP 01</p><h2>{isBusiness?"What are you working on?":"Your evidence, at a glance."}</h2><p>{service.overview}</p>{!isBusiness&&<div className="notice">Tick the items you believe apply to you. This is an information checklist, not an eligibility test. You can continue with no selections if you are unsure. Ask an authorized legal professional about legal requirements and strategy.</div>}{service.groups.map((g,gi)=><fieldset className="evidence-group" key={g.title}><legend>{g.title}</legend><p>{g.description}</p><div className="checklist">{g.items.map((label,i)=>{const key=`${gi}-${i}`;return <label className={`check-row ${selected.includes(key)?"checked":""}`} htmlFor={`e-${key}`} key={key}><Checkbox id={`e-${key}`} checked={selected.includes(key)} onCheckedChange={v=>setSelected(prev=>v===true?[...prev,key]:prev.filter(x=>x!==key))}/><span>{label}</span></label>})}</div></fieldset>)}{service.source&&<p className="source-note">General reference: <a className="content-link" target="_blank" rel="noreferrer" href={service.source}>{service.sourceLabel}</a>. Requirements can change; consult the official guidance.</p>}</div>}
 {step===2&&<div className="panel"><p className="eyebrow">STEP 02</p><h2>{isBusiness?"Tell us about your project.":"Introduce yourself and your work."}</h2><p className="form-intro">{isBusiness?"Share a brief description so we can prepare for a useful conversation.":"Your CV helps us understand your background before your writing consultation."}</p><div className="form-grid"><label className="field">Full name *<input autoComplete="name" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Email address *<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Phone number (optional)<input type="tel" autoComplete="tel" maxLength={60} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="field">{isBusiness?"Project or organization":"Professional field"} *<input required maxLength={200} value={field} onChange={e=>setField(e.target.value)} placeholder={isBusiness?"e.g. Business plan for a consultancy":"e.g. Biomedical research"}/></label></div><label className="field">{isBusiness?"Project brief":"What would you like to discuss?"}{isBusiness?" *":" (optional)"}<textarea required={isBusiness} maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={isBusiness?"Describe the document, its audience and your target timeline.":"Tell us about your writing needs and the documents you already have."}/></label><div className="upload-area"><FileText size={28}/><label className="field">{isBusiness?"Supporting document (optional)":"Attach your CV *"}<input aria-label={isBusiness?"Supporting document":"Attach your CV"} type="file" accept=".pdf,application/pdf" onChange={e=>chooseFile(e.target.files?.[0])}/></label>{file?<p className="file-name">Selected: {file.name} · {(file.size/1024).toFixed(0)} KB <button type="button" className="content-link" onClick={()=>setFile(null)}>Remove</button></p>:null}<p className="tiny">PDF only · Maximum 5 MB. Upload documents without passport numbers, Social Security numbers or unrelated sensitive information.</p></div><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div></div>}
 {step===3&&<div className="panel"><p className="eyebrow">STEP 03</p><h2>Make time for your next step.</h2><p className="form-intro">Choose a 40-minute appointment. All times are Eastern Time (EST/EDT), with daylight saving changes applied automatically.</p><div className="availability-head"><span><CalendarDays size={18}/> Available appointments</span><Button variant="ghost" type="button" disabled={loading||saving} onClick={()=>void loadSlots()} aria-label="Refresh appointment availability"><RefreshCw size={16}/></Button></div>{loading?<p role="status">Loading appointment availability…</p>:slots.length===0?<p>No appointments are currently available. Please try refreshing, or contact Obotan to arrange a time.</p>:<><label className="field">Choose a date<Select value={date} onValueChange={v=>{setDate(v);setChosen("")}}><SelectTrigger className="w-full min-h-12"><SelectValue placeholder="Select a date"/></SelectTrigger><SelectContent>{[...new Map(slots.map(s=>[s.date,s.dayLabel])).entries()].map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label><RadioGroup value={chosen} onValueChange={setChosen} className="time-grid" aria-label="Appointment time">{slots.filter(s=>s.date===date).map(s=><label className={`time-option ${chosen===String(s.start)?"chosen":""}`} key={s.start}><RadioGroupItem value={String(s.start)} aria-label={s.timeLabel}/><span>{s.timeLabel}</span></label>)}</RadioGroup></>}<div className="review-summary"><h3>Your consultation details</h3><dl><div><dt>Service</dt><dd>{service.label}</dd></div><div><dt>Name</dt><dd>{name}</dd></div><div><dt>Email</dt><dd>{email}</dd></div><div><dt>Checklist</dt><dd>{selected.length} self-reported selections</dd></div><div><dt>Document</dt><dd>{file?.name||"No document attached"}</dd></div></dl></div><label className="consent-row"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Acknowledge scope and privacy"/><span>I am booking research, document review and writing support. I agree to the <a className="content-link" target="_blank" href="/privacy">privacy and service scope</a> and consent to Obotan using my information and document for this consultation.</span></label><p className="micro">Any paid work, fees and deliverables will be agreed separately.</p></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}<div className="form-actions">{step>1?<Button variant="outline" type="button" className="cta" disabled={saving} onClick={()=>{setStep(step-1);setError("")}}><ArrowLeft/> Back</Button>:<span className="tiny muted">{selected.length} selected</span>}<Button type="submit" className="cta" disabled={saving||(step===3&&(loading||!chosen))}>{saving?"Saving your booking…":step===1?"Continue to documents":step===2?"Choose a consultation":"Book 40-minute consultation"}<ArrowRight/></Button></div>
 </form></section><aside className="intake-aside"><div className="consult-card"><Clock3 size={26}/><h2>A focused<br/>40 minutes.</h2><p>Discuss your CV, documents and writing needs with Obotan Consult.</p><dl><div><dt>Wednesday</dt><dd>6:00–10:00 pm</dd></div><div><dt>Thursday</dt><dd>6:00–10:00 pm</dd></div><div><dt>Saturday</dt><dd>9:00 am–12:00 pm</dd></div></dl><span className="tiny">Eastern Time · EST/EDT</span><div className="consult-foot">No client account required</div></div><div className="scope-note"><ShieldCheck size={22}/><h3>Support shaped around your work.</h3><p>Bring your CV, ideas and supporting documents. We can help with research, evidence organization, writing and document development.</p></div></aside></div>;
}



