import {timingSafeEqual, randomBytes, createHash} from 'node:crypto';

export const ADMIN_COOKIE = '__Host-obotan-admin';
export const SESSION_SECONDS = 4 * 60 * 60;
export function digest(value:string){return createHash('sha256').update(value).digest('hex')}
export function randomToken(){return randomBytes(32).toString('hex')}
// Only use machine-generated 256-bit passwords with this verifier. A fast hash
// is NOT suitable for ordinary human-chosen passwords.
export function generatePassword(){return `obotan_${randomBytes(32).toString('base64url')}`}
export function validHash(value:unknown):value is string{return typeof value==='string'&&/^random-v1\$[a-f0-9]{32}\$[a-f0-9]{64}$/.test(value)}
export async function hashPassword(password:string){
 if(!/^obotan_[A-Za-z0-9_-]{43}$/.test(password))throw new Error('Use the password generated by the setup tool.');
 const salt=randomBytes(16).toString('hex');
 return `random-v1$${salt}$${digest(`obotan-admin-v1:${salt}:${password}`)}`;
}
export async function verifyPassword(password:string,stored:string){
 if(!validHash(stored)||password.length>128)return false;
 const [,salt,hash]=stored.split('$');
 return timingSafeEqual(Buffer.from(digest(`obotan-admin-v1:${salt}:${password}`),'hex'),Buffer.from(hash,'hex'));
}
export function sessionToken(headers:Headers){
 const token=headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${ADMIN_COOKIE}=`))?.slice(ADMIN_COOKIE.length+1);
 return token&&/^[a-f0-9]{64}$/.test(token)?token:null;
}
export function sessionCookie(token:string,seconds=SESSION_SECONDS){return `${ADMIN_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${seconds}`}
