export type EvidenceGroup = { title: string; description: string; items: string[] };
export type Service = { slug: string; label: string; title: string; description: string; overview: string; groups: EvidenceGroup[]; source?: string; sourceLabel?: string };
export const services: Service[] = [
 {slug:"business-docs",label:"Business Docs",title:"Give your ideas a clear direction.",description:"Research and professional writing that help you explain your goals, communicate your work and plan your next step.",overview:"Tell us what you are developing, who it is for and what you want it to achieve. We can discuss research, structure, writing and editing during your consultation. Scope, timing and fees are agreed separately.",groups:[{title:"What would you like support with?",description:"Choose all that apply to your project.",items:["Business plan development","Research and analytical reports","Policy documents and briefs","Professional document writing","Editing and document organization","Proposals and project documentation"]}]},
 {slug:"eb1a",label:"EB1A",title:"Make your achievements clearly understood.",description:"CV and document review, research, and petition writing support for extraordinary ability materials.",overview:"EB-1A concerns extraordinary ability in science, art, education, business or athletics. A major internationally recognized award, or evidence satisfying at least three regulatory categories, addresses the initial evidence step. USCIS also evaluates the full record; ticking boxes does not establish eligibility or guarantee approval. Self-petitioning is possible. Obotan does not choose your category or file your petition.",source:"https://www.ecfr.gov/current/title-8/chapter-I/subchapter-B/part-204/subpart-A/section-204.5#p-204.5(h)",sourceLabel:"8 CFR 204.5(h) — extraordinary ability",groups:[
 {title:"Major award",description:"This is an alternative initial evidence route, separate from the ten categories below.",items:["A major, internationally recognized award"]},
 {title:"Evidence categories",description:"Tick items you believe you can support with documents. Your selections are self-reported, not a legal assessment.",items:["Nationally or internationally recognized awards for excellence","Memberships requiring outstanding achievements judged by recognized experts","Professional or major-media coverage about you and your work","Judging others’ work in your field or an allied field","Original contributions of major significance in your field","Scholarly articles you authored in professional, trade or major publications","Your work displayed at artistic exhibitions or showcases","Leading or critical roles in distinguished organizations","High pay compared with others in your field","Commercial success in the performing arts"]},
 {title:"Additional context",description:"These items are not extra categories toward the three-category threshold.",items:["Evidence of sustained national or international acclaim","Plans to continue work in my area of expertise in the United States","Comparable evidence where the listed standards do not readily apply to my occupation"]}]},
 {slug:"eb1b",label:"EB1B",title:"Put your academic contribution into words.",description:"Research, CV review and writing support for outstanding professor and researcher documentation.",overview:"EB-1B requires a petitioning U.S. employer, international recognition as outstanding, qualifying teaching or research experience, and a qualifying job offer. At least two of the six evidence categories are generally required, followed by evaluation of the full record. This checklist organizes information for a writing consultation; it is not an eligibility determination. Obotan does not act as petitioner or legal representative.",source:"https://www.ecfr.gov/current/title-8/chapter-I/subchapter-B/part-204/subpart-A/section-204.5#p-204.5(i)",sourceLabel:"8 CFR 204.5(i) — outstanding professors and researchers",groups:[
 {title:"Employer and experience",description:"Select the statements for which you have supporting information.",items:["A U.S. employer intends to petition for me","At least three years of qualifying teaching or research experience","International recognition as outstanding in my academic field","An offer of a tenured or tenure-track teaching role, or qualifying permanent research role","For a private employer: its research unit has at least three full-time researchers and documented academic accomplishments"]},
 {title:"Academic evidence categories",description:"Tick all categories you believe your documents support.",items:["Major prizes or awards for outstanding academic achievement","Memberships requiring outstanding academic achievement","Professional publications by others about my academic work","Judging the work of others in my field or an allied academic field","Original scientific or scholarly research contributions","Scholarly books or articles in internationally circulated scholarly journals"]},
 {title:"Additional context",description:"Comparable evidence may be relevant when the standards do not readily apply.",items:["Other comparable evidence to discuss"]}]},
 {slug:"eb2",label:"EB2 · NIW",title:"Explain your endeavor. Show its purpose.",description:"Research, proposed endeavor documents, business plans and writing support for National Interest Waiver materials.",overview:"An NIW request first requires an EB-2 basis: an advanced-degree professional or a person of exceptional ability. It then requires evidence addressing all three NIW factors. An NIW can waive the job-offer and labor-certification requirements and allows self-petitioning. This page supports NIW only. Selections organize your documents; they do not establish eligibility.",source:"https://www.uscis.gov/policy-manual/volume-6-part-f-chapter-5",sourceLabel:"USCIS Policy Manual — EB-2 and National Interest Waivers",groups:[
 {title:"Advanced-degree professional basis",description:"The intended occupation must qualify as a profession. The two education routes below are alternatives, not cumulative requirements.",items:["A U.S. advanced degree or foreign equivalent relevant to the proposed work","A U.S. bachelor’s degree or foreign equivalent plus five years of progressive post-degree experience in the specialty","My intended occupation normally requires at least a bachelor’s degree or its equivalent"]},
 {title:"Exceptional-ability basis",description:"An alternative to the advanced-degree basis. Generally at least three categories plus an assessment of the full record are needed; comparable evidence may apply.",items:["An academic record relating to my area of exceptional ability","Employer letters documenting at least ten years of full-time experience","A professional license or certification","Pay demonstrating exceptional ability","Membership in professional associations","Recognition of achievements and significant contributions by peers, government or professional/business organizations"]},
 {title:"National Interest Waiver factors",description:"Tick the areas for which you have evidence to discuss. All three factors matter; these are not interchangeable.",items:["My proposed endeavor has substantial merit and national importance","My background and progress position me to advance the endeavor","On balance, waiving the job-offer and labor-certification requirements would benefit the United States"]}]}];
export function findService(slug:string){return services.find(s=>s.slug===slug)}
export function evidenceOptions(service:Service){return service.groups.flatMap((g,gi)=>g.items.map((label,i)=>({id:`${gi}-${i}`,label,group:g.title})))}
export const DISCLOSURE_VERSION="2026-09-23-v3-email";

